apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-app
          image: python:3.9-slim
          command: ["python", "/app/app.py"]
          env:
            - name: MYSQL_HOST
              value: mysql-poc-service  # The name of the mysql-poc- service
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-poc-secret
                  key: user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-poc-secret
                  key: password
            - name: MYSQL_DATABASE
              value: flaskdb  # The database that Flask will connect to
          volumeMounts:
            - name: flask-app-code
              mountPath: /app
      volumes:
        - name: flask-app-code
          configMap:
            name: flask-app-config
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: flask-app
